### PR TITLE
Sync single user picker with Address Book in award/smite dialogs

### LINKED ISSUE #3641: With Address Book enabled, all SingleUserPicker fields should filter members
## Steps to reproduce

1. Add a Member to the Address Book
2. Go to the Smite or Award modals
3. Try to select a member using the `SingleUserPicker`
4. The picker will show all members and not the filtered members as of the Address Book

This should apply to all `SingleUserPicker` fields, so this filter may work better at a higher level.

## Expected behaviour

* All `SingleUserPicker` fields should filter members when the Address Book is enabled

## Actual behaviour

* The `SingleUserPicker` is not filtering addresses in the Address Book

user-picker-filter

### PR DESCRIPTION
**Pull request by willm30**
## Description

This PR  ensures that when the Address Book is enabled, the single user picker in the Award/Smite dialogs shows verified members instead of all members. When the Address Book is inactive, or no members have been added, the single user picker in both components should show all colony members. 

Note: this was already happening in the Create Payment dialog. I have extracted this logic for reuse in the Award/Smite components.
 
To test: 

1. With no members added, verify that the `SingleUserPicker` in the Award/Smite show all users in the colony. 
2. Add a member or two to the address book. Now verify the `SingleUserPicker` only shows those members. 
3. Turn off the address book. Now verify that the `SingleUserPicker` is showing all users again.

**Changes** 🏗

`CreatePaymentDialog.tsx`: Extracted the `verifiedUsers` logic for reuse in award/smite.
`ManageReputationContainer.tsx`: Added the `ColonyMembers` prop so that when the component loads, `ColonyMembers` is defined. This ensures that the selected user doesn't rerender after the component has been opened and therefore avoids a "flashing" in the ui. Also added the `verifiedUsers` logic. 
`ColonyHomeActions.tsx`: I moved the ColonyMembers query here because this contains the loading component nearest to the ManageReputation Container.
`useSelectedUser.ts`: updated to take an array of `AnyUser` (making it compatible with an array of verified or subscribed users)

**Additions**

`verifiedRecipients.ts`: Extracted logic for filtering subscribed (i.e. all) users by whether they're verified or not.

Resolves #3641

**Note:** The issue says that this should apply to all `SingleUserPicker` instances however after checking this with Arren we agreed that it should only apply to the Payments and Award/Smite dialogs for now (see issue comments).

### CODE REVIEW

**Comment by danbr** [comment]
@willm30 Maybe my expectation is wrong?
The updates seem to be working except when I deactivate the address book. The list of potential awardees are still restricted.

Empty address book, with 1 contributor & 1 watcher
Screenshot 2022-08-15 at 15 11 22
With User2 added to address book & deactivated
Screenshot 2022-08-15 at 15 10 22
User options, expecting Dan & User2 to be displayed
Screenshot 2022-08-15 at 15 18 25

**Comment by willm30** [comment]
> @willm30 Maybe my expectation is wrong? The updates seem to be working except when I deactivate the address book. The list of potential awardees are still restricted.

@danbr Did you refresh the browser after deactivating the address book? For me, I need to do this first, then the updates propagate and the form shows all users. (Incidentally, I would like to open an issue to update the fetch-policies of the relevant queries so a browser refresh isn't needed after adding a member to the address book to see the updated address book).

**Comment by danbr** [comment]
> > @willm30 Maybe my expectation is wrong? The updates seem to be working except when I deactivate the address book. The list of potential awardees are still restricted.
> 
> @danbr Did you refresh the browser after deactivating the address book? For me, I need to do this first, then the updates propagate and the form shows all users. (Incidentally, I would like to open an issue to update the fetch-policies of the relevant queries so a browser refresh isn't needed after adding a member to the address book to see the updated address book).

@willm30 Thanks for the suggestion. I re-setup, and did several page refreshes and the behaviour remained the same with only 1 address shown. When she is available, i will ask @chinins to test, perhaps it will work for her.

File: src/modules/dashboard/components/Dialogs/AwardAndSmiteDialogs/ManageReputationContainer/ManageReputationContainer.tsx [hunk 1]
```diff
@@ -163,6 +169,9 @@ const ManageReputationContainer = ({
               isVotingExtensionEnabled={isVotingExtensionEnabled}
               back={() => callStep(prevStep)}
               ethDomainId={ethDomainId}
+              verifiedUsers={
+                (isWhitelistActivated && verifiedUsers) || subscribedUsers
+              }
```
Comment (willm30) [inline src/modules/dashboard/components/Dialogs/AwardAndSmiteDialogs/ManageReputationContainer/ManageReputationContainer.tsx:174]: @danbr Hmm, interesting. I am unable to reproduce. With a contributor and a watcher, I add the watcher to the address book, then deactivate the address book via the toggle switch, and after a browser refresh on the ColonyHome page I can see both users in the Award/Smite and CreatePayment dialogs. 

This is where I implement the check for whether the whitelist is activated. It should pass the form (and therefore the Single User Picker) all users (i.e `subscribedUsers`) if `isWhitelistActivated` is false (even if there is a member added to the address book).  Maybe you can spot something I'm overlooking?

Comment (danbr) [reply src/modules/dashboard/components/Dialogs/AwardAndSmiteDialogs/ManageReputationContainer/ManageReputationContainer.tsx:174]: @willm30 Finally, I deleted my local branch and now its behaving as expected, thankfully!! I'll review the code next....

**Review by danbr — APPROVED** [review]
Looks good. Working well..... Nice job.

File: src/modules/dashboard/components/ColonyHomeActions/ColonyHomeActions.tsx [hunk 2]
```diff
@@ -79,6 +80,13 @@ const ColonyHomeActions = ({ colony, ethDomainId }: Props) => {
     variables: { address: colony.colonyAddress },
   });
 
+  const {
+    data: colonyMembers,
+    loading: isLoadingColonyMembers,
+  } = useMembersSubscription({
+    variables: { colonyAddress: colony.colonyAddress },
+  });
```
Comment (chinins) [inline src/modules/dashboard/components/ColonyHomeActions/ColonyHomeActions.tsx:88]: First of all, the approach should be similar in all cases - both for Smite/Award dialogs and for Create payment dialog which is not the case right now. There is no reason for the approaches to be different.

Secondly, I think that the query shouldn't be moved here. Will we now move all the queries from all of the dialogs here? It doesn't make sense. I think that it should removed from here and the same approach should be takes as for the Create payment dialog.

File: src/modules/dashboard/components/Dialogs/AwardAndSmiteDialogs/ManageReputationContainer/ManageReputationContainer.tsx [hunk 3]
```diff
@@ -48,9 +49,12 @@ const ManageReputationContainer = ({
...
   const history = useHistory();
 
-  const { data: colonyMembers } = useMembersSubscription({
-    variables: { colonyAddress },
-  });
+  const { subscribedUsers } = colonyMembers;
+
+  const verifiedUsers = useMemo(() => {
+    const verifiedAddresses = colony.whitelistedAddresses;
+    return getVerifiedUsers(verifiedAddresses, subscribedUsers);
```
Comment (chinins) [inline src/modules/dashboard/components/Dialogs/AwardAndSmiteDialogs/ManageReputationContainer/ManageReputationContainer.tsx:56]: You can just pass `colony.whitelistedAddresses` to the function, there is no need to create a variable.

File: src/modules/dashboard/components/Dialogs/AwardAndSmiteDialogs/ManageReputationContainer/ManageReputationContainer.tsx [hunk 4]
```diff
@@ -163,6 +169,9 @@ const ManageReputationContainer = ({
               isVotingExtensionEnabled={isVotingExtensionEnabled}
               back={() => callStep(prevStep)}
               ethDomainId={ethDomainId}
+              verifiedUsers={
+                (isWhitelistActivated && verifiedUsers) || subscribedUsers
```
Comment (chinins) [inline src/modules/dashboard/components/Dialogs/AwardAndSmiteDialogs/ManageReputationContainer/ManageReputationContainer.tsx:173]: You should use ternary in cases like this (as per my other comments)

**Review by chinins — CHANGES_REQUESTED** [review]
As per my direct comments.

File: src/modules/dashboard/components/ColonyHomeActions/ColonyHomeActions.tsx (hunk 2 above)
Comment (willm30) [reply src/modules/dashboard/components/ColonyHomeActions/ColonyHomeActions.tsx:88]: @chinins The intention here is to ensure that `colonyMembers` is defined when the component mounts. If it isn't, as is the case when you run the query in the component, you can get a slight flashing in the UI, as below (see recipient field): 

flashingRep

If the colonyMembers data is undefined, then the selectedUser will also be undefined. Once the query returns, the component rerenders and the selectedUser gets set properly -- hence the flash. 

The reason this wouldn't be necessary in the CreatePayment dialog is because no user is preselected, so the effect of colonyMembers being undefined initially is invisible -- by the time a user has opened the SingleUserPicker, the data is there. 

What do you think? I'm easy either way, but in general prefer to avoid UI flashes, even small ones.

Comment (chinins) [reply src/modules/dashboard/components/ColonyHomeActions/ColonyHomeActions.tsx:88]: To be honest, I don't mind this flash. I think we shouldn't be add queries in improper places just to avoid it. You can have a loading spinner instead for the whole dialog if you want. And then when we move to the cdapp with new react features there either won't be any flashing at all, just a tiny delay in showing the form, or you will have a spinner for a couple of seconds.

**Comment by willm30** [comment]
> As per my direct comments.

@chinins Have updated and restored the Memebrs Query to the component. Please review when you get a moment.

**Review by Julianahlk — APPROVED** [review]
It works well for me!

**Review by ArmandoGraterol — APPROVED** [review]
Working as expected! Nice job

**Review by chinins — APPROVED** [review]
Very nice - much cleaner, I prefer it this way.
