### PR TITLE
Update `contributorsAndWatchers` query resolver to fix members with reputation list

### LINKED ISSUE #3507: Contributors are being shown as Watchers
## Steps to reproduce

1. Create a colony.
2. Generate reputation for the root user.
3. Join the colony with a fresh user.
4. Generate reputation for the second user.
5. Take a look at the contributors vs watchers section in the aside or the Members page.

## Expected behaviour

* The second, newer member with reputation, should appear along with the first user on the contributor's side.

## Actual behaviour

* The second user appears on the watcher's side even though it has reputation, and this is the case for any other user that doesn't have domain roles but has reputation.

FireShot Capture 627 - Members - Colony - wonker - localhost

## Suggestions

* Tried to find the source of this bug, managed to track it down to the `colonyMembersWithReputation` resolver in the `colony` file. The resolver is _always_ returning an empty array as if there were no members with reputation, including the root user.

### PR DESCRIPTION
**Pull request by chinins**
## Description

This PR fixes the resolver of the `contributorsAndWatchers` query.

I have noticed that `colonyMembersWithReputation` resolver takes `COLONY_TOTAL_BALANCE_DOMAIN_ID` as a default domain. In this case it will always return an empty list. I put root domain id as a default because I assume we want to have all of the members with reputation if no domain id is passed and having always no addresses returned in this case doesn't make sense.

**Changes** 🏗

- update `contributorsAndWatchers` resolver
- update `colonyMembersWithReputation` resolver

resolves #3507

### CODE REVIEW

File: src/data/resolvers/colony.ts [hunk 1]
```diff
@@ -439,17 +442,6 @@ export const colonyResolvers = ({
...
-      //   VerifiedUsersQuery,
-      //   VerifiedUsersQueryVariables
-      // >({
-      //   query: VerifiedUsersDo,
-      //   variables: {
-      //     colonyAddress,
-      //   },
-      //   fetchPolicy: 'network-only',
-      // });
-
```
Comment (rdig) [inline src/data/resolvers/colony.ts:452]: :+1:

**Review by rdig — APPROVED** [review]
Good fix!

Does this also fix @ArmandoGraterol 's #3507 by chance ?

**Comment by chinins** [comment]
> Good fix!
> 
> Does this also fix @ArmandoGraterol 's #3507 by chance ?

It is a fix for #3507, I talked to Armando yesterday and suggested to fix it today in a separate PR

**Review by dit7ya — APPROVED** [review]
LGTM. :)
