### PR TITLE
Revert form names for Colony creation & improve validation error msgs

### LINKED ISSUE #3634: Error thrown when adding an address to address book
## Steps to reproduce

1. Add an address to address book

Screenshot 2022-07-14 at 15 29 22

### PR DESCRIPTION
**Pull request by danbr**
## Description

- This PR fixes a bug that prevents addresses from being added to the address book, it also caused problems when editing colony details.
- The issues were caused by the changing of form names used during the creation of a Colony in #3606.

This PR reverts the names back to their original which fixes #3634
Screenshot 2022-07-16 at 19 13 17

 And also resolves the issues listed in #3583, where validation messages should match the input field label
Screenshot 2022-07-16 at 11 45 33

## Testing

1. Create a new Colony
2. Add an address to address book (Manage Teams->Manage address book)

Resolves #3634 & #3583

### CODE REVIEW

**Review by chinins — APPROVED** [review]
Good fix! Not easy to find the reason I'm sure.

File: src/modules/dashboard/components/CreateColonyWizard/StepColonyName.tsx [hunk 1]
```diff
@@ -197,18 +222,18 @@ const StepColonyName = ({
             <div className={styles.nameForm}>
               <Input
                 appearance={{ theme: 'fat' }}
-                name="colonyName"
+                name="displayName" // In Metatdata corresponds to: colonyDisplayName
```
Comment (Julianahlk) [inline src/modules/dashboard/components/CreateColonyWizard/StepColonyName.tsx:225]: Nice comment, great reminder that this name is quite important.

**Review by Julianahlk — APPROVED** [review]

**Review by ArmandoGraterol — APPROVED** [review]
LGTM :+1:
