### PR TITLE
Fix the finalize motion error condition

### LINKED ISSUE #3307: Unnecessary error that doesn't allow to finalise mint tokens motion
The error appears when the colony funds is less than the amount of tokens to mint. This prevents finalising the motion.

### PR DESCRIPTION
**Pull request by chinins**
## Description

Update the condition that prevents finalising motion.

To test you need to mint an mount that is more than the current colony token balance

Before

Screenshot 2022-04-13 at 17 09 12

After

Screenshot 2022-04-13 at 17 07 50

resolves #3307

### CODE REVIEW

File: src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/FinalizeMotionAndClaimWidget.tsx [hunk 1]
```diff
@@ -194,6 +194,7 @@ const FinalizeMotionAndClaimWidget = ({
     const domainBalance = bigNumberify(domainBalanceData?.domainBalance || '0');
 
     if (
+      actionType !== ColonyMotions.MintTokensMotion &&
```
Comment (rdig) [inline src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/FinalizeMotionAndClaimWidget.tsx:197]: I don't really understand how this fix works. 

We're filtering out the Mint Motion as an action from the _Finalize_ button validation logic, correct ?

That means that we're not really fixing the underlying problem, but just brute forcing it for the Mint Motion, where this problem shows up

I feel like there is something else at play here that is preventing the Motion to be finalized if you're minting more tokens than your current balance.

**Review by rdig — CHANGES_REQUESTED** [review]
Possibly this is the correct approach, but I don't understand it _(or understand something else)_

So this "require changes" is more to help me understand this problem, rather than requiring actual code changes :)

File: src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/FinalizeMotionAndClaimWidget.tsx (hunk 1 above)
Comment (chinins) [reply src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/FinalizeMotionAndClaimWidget.tsx:197]: It's just not applicable to Min tokens motion. We can finalise motion even if the balance is zero. There is nothing to prevent us from it. In other situations we need the token balance be more than what we need to pay/transfer. Otherwise we'll have a contract error - we can transfer/pay more than we our balance. Again for mint tokens it's not important as we don't need any balance to "transfer from".
Let me know if it's still not clear

**Review by ArmandoGraterol — APPROVED** [review]
Working as expected! Nice work

**Review by rdig — APPROVED** [review]
Still can't quite wrap my head around it, but I don't really want to keep blocking it.
