### PR TITLE
Fix: confirm button flashing on dialog open

### LINKED ISSUE #3632: Bug: "ban / unban address" button flashing
## Steps to reproduce

1. Go to `{colony_home}/members/`  and click either ban address or unban address. 
2. As the modal opens, the confirm button flashes the colour corresponding to whether it's ban / unban. 

## Expected behaviour

No colour flashing should be observable

## Actual behaviour

Button is flashing 

flashing

### PR DESCRIPTION
**Pull request by willm30**
## Description

Small pr to fix a small bug with the confirm button of the Ban User form that was flashing upon first open. Now, when opening the dialog via ban / unban address, the confirm button does not flash.

**Changes** 🏗

* Form is now disabled if the input is an empty string.

## Screenshot
_Undesired flashing_

flashing

Resolves #3632

### CODE REVIEW

**Review by ArmandoGraterol — CHANGES_REQUESTED** [review]
Unfortunately, it can't be this simple:
FireShot Capture 676 - Members - Colony - wonker - localhost

Now when I want to ban a user through the "Ban user" option in the 3 dots tooltip of the member list I can't because the user address is prefilled and therefore the form is not dirty

**Comment by willm30** [comment]
> Now when I want to ban a user through the "Ban user" option in the 3 dots tooltip of the member list I can't because the user address is prefilled and therefore the form is not dirty

Nice catch. Should be fixed now (still fairly simple 🙂).

**Review by ArmandoGraterol — APPROVED** [review]
Nice one! It's working properly now. I like Dan's suggestion, it's even more simple than what we currently have :)

**Review by arrenv — APPROVED** [review]
Looks good, I also prefer Dan's suggestion.

File: src/modules/core/components/Comment/Dialogs/BanUser/BanUser.tsx [hunk 1]
```diff
@@ -175,58 +175,66 @@ const BanUser = ({
...
-                disabled={
-                  loadingBannedUsers || loadingBanAction || isSubmitting
-                }
+      {({
+        isValid,
+        isSubmitting,
+        values,
+        submitForm,
+      }: FormikProps<FormValues>) => {
+        const isEmptyString = values.userAddress === '';
```
Comment (chinins) [inline src/modules/core/components/Comment/Dialogs/BanUser/BanUser.tsx:184]: This is not good practice to have a stateless variable like this.

**Review by chinins — APPROVED** [review]
Please, make sure that you update it based on Dan's suggesiton.

**Comment by willm30** [comment]
@danbr When you go to ban an address that is prepopulated, there are a couple of renders where the initial values are actually `{userAddress: undefined}`, which means that with `!values.userAddress` you still get a flash. 

ban-user-flash
 

Is that ok or should I do something like `disabled={!isValid || isSubmitting || values.userAddress === ''}`?

**Comment by chinins** [comment]
> @danbr When you go to ban an address that is prepopulated, there are a couple of renders where the initial values are actually `{userAddress: undefined}`, which means that with `!values.userAddress` you still get a flash.
> 
> 
> Is that ok or should I do something like `disabled={!isValid || isSubmitting || values.userAddress === ''}`?

That's fine as well
