### PR TITLE
Fix inbox fetching (and show username registered notification)

### LINKED ISSUE #1404: Show inbox notification for current user ENS registered label
Notification about created username doesn't show up. It also should be visible in inbox fullscreen view.

### PR DESCRIPTION
**Pull request by JamesLefrere**
## Description

This PR makes various fixes to inbox fetching, such that inbox items are fetched:

* On log in
* On username creation
* On colony subscription

rather than adding inbox items manually.

Hopefully this will go some way to convering this to a subscription of changes rather than discrete fetches.

It also adds a notification when the username is registered.

**Changes** 🏗
* Adjust colony/user creation sagas such that inbox items are fetched on success, rather than creating inbox items manually
* Adjust inbox items fetching such that the user profile creation is handled as an event, and that the query can complete if other user stores are not available yet
* Adjust inbox items state such that a `DataRecord` is used, and fetch the data in the component
* Fix normalizer types
* Fix duplicate `takeEvery` statements in user sagas

**Deletions** ⚰️

* Remove `putNotification` util
* Remove `INBOX_ITEMS_ADD` action

Resolves #1404

### CODE REVIEW

File: src/modules/dashboard/sagas/colony.ts [hunk 1]
```diff
@@ -579,6 +579,11 @@ export default function* colonySagas() {
     colonyTokenBalanceFetch,
   );
   yield takeEvery(ActionTypes.COLONY_VERSION_UPGRADE, colonyUpgradeContract);
+  yield takeEvery(ActionTypes.COLONY_SUB_START, colonySubStart);
```
Comment (JamesLefrere) [inline src/modules/dashboard/sagas/colony.ts]: These were moved up so the comment below made sense.

File: src/modules/users/reducers/currentUser/notifications.ts [hunk 2]
```diff
@@ -4,22 +4,18 @@ import {
   UserNotificationMetadataRecordType,
 } from '~immutable/index';
 
-type State = UserNotificationMetadataRecordType;
-
-const currentUserNotificationsReducer: ReducerType<State> = (
-  state = UserNotificationMetadataRecord(),
-  action,
-) => {
+const currentUserNotificationsReducer: ReducerType<
```
Comment (JamesLefrere) [inline src/modules/users/reducers/currentUser/notifications.ts]: Just a tiny tweak here for readability

File: src/modules/users/sagas/inbox.ts [hunk 3]
```diff
@@ -132,6 +136,57 @@ function* markNotificationAsRead({
   return null;
 }
 
+function* inboxItemsFetch({ meta }: Action<ActionTypes.INBOX_ITEMS_FETCH>) {
```
Comment (JamesLefrere) [inline src/modules/users/sagas/inbox.ts]: This was also moved from the `users` file, since it seems to belong here more.

File: src/modules/users/sagas/user.ts [hunk 4]
```diff
@@ -756,11 +711,8 @@ function* userSubscribedColoniesSubStart({
 
 /* eslint-disable max-len,prettier/prettier */
 export function* setupUsersSagas() {
-  yield takeEvery(ActionTypes.INBOX_ITEMS_FETCH, inboxItemsFetch);
```
Comment (JamesLefrere) [inline src/modules/users/sagas/user.ts]: Duplicates! This could have been causing problems.

File: src/modules/users/components/Inbox/InboxContent/InboxContent.tsx [hunk 5]
```diff
@@ -55,19 +61,19 @@ const InboxContent = () => {
           />
         </div>
         <div className={styles.inboxContainer}>
-          {inboxItems.length === 0 ? (
-            <div className={styles.loadingText}>
-              <FormattedMessage {...MSG.loadingInbox} />
-              <DotsLoader />
-            </div>
-          ) : (
+          {inboxItems ? (
```
Comment (rdig) [inline src/modules/users/components/Inbox/InboxContent/InboxContent.tsx]: Very nice, no longer infinite dots spinner
