### PR TITLE
Fix task attributes cache

### LINKED ISSUE #2012: Changing task assignee does not update those values in the task list
### Description

This issue encompasses 2 bugs. Changing a tasks assignee:

1. Does not update those values until after a page refresh.
2. Does not add task to "my tasks" list if assigned to one's self

### Suggestion

This might be solved by adding in a `refetchQueries` directive, updating the cache directly, adjusting mutation response parameters, or some combination of the aforementioned solutions.

### Demo

bug-assignee-not-updating

### PR DESCRIPTION
**Pull request by ceolson01**
## Description

This PR fixes two particular issues, and likely prevents a couple of related cache bugs from surfacing in the future.

Most notably - in cases where an expanded user and their address are both fields on query types, we now accept both fields in mutation results. This solves some cache issues related to task worker assignment not updating immediately in task lists.

Also, this PR ensures that a task is added or removed from the user task list when they've assigned or unassigned themselves, respectively.

Closes #2012

### CODE REVIEW

File: src/modules/dashboard/components/TaskEditDialog/TaskEditDialog.tsx [hunk 1]
```diff
@@ -212,15 +216,31 @@ const TaskEditDialog = ({
...
         );
 
+      const refetchSelfTasks = [
+        {
+          query: UserTasksDocument,
+          variables: {
+            address: walletAddress,
+          } as UserTasksQueryVariables,
+        },
+      ];
```
Comment (ceolson01) [inline src/modules/dashboard/components/TaskEditDialog/TaskEditDialog.tsx]: In theory, this could be done as a `cacheUpdates` function, but would be quite messy, as it would require us to expand some of our existing queries unnecessarily, just for when this case occurs (user assigns or unassigns themselves). I can't imagine this is going to happen often enough to warrant such implementation.
