### PR TITLE
Fix admin permissions hover

### LINKED ISSUE #1852: Hover state missing for admins without permission
## Steps to reproduce

1. Permissions tab
2. Open a user who you do not have permission to edit
3. No idea why this is happening

## Expected behaviour

* We have a few designs for hover states to show the user that they do not have permission. We can use this hover state for any role (i.e. "You do not have permission to set the administrative role.")

You do nothave permission

## Actual behaviour

* There is no hover state so when I go to use it, it feels like the modal is just frozen or broken. 

Colony

### PR DESCRIPTION
**Pull request by ceolson01**
## Description

This PR adds a tooltip (er... `Popover`, to be technical) when a user hovers over a disabled permission in the colony permissions edit dialog.

**New stuff** ✨

* `PermissionCheckbox` component

**Changes** 🏗

* Use `PermissionCheckbox` component in `ColonyPermissionsEditDialog`
* Improve clarity of some logic regarding state updates
* Use global i18n messages for buttons and some roles.

**Demo** 🎥 

Permissions Hover

Closes #1852

### CODE REVIEW

**Comment by chmanie** [comment]
I should base my 1850 on this

File: src/modules/admin/components/Permissions/ColonyPermissionEditDialog.tsx [hunk 1]
```diff
@@ -267,9 +236,9 @@ const ColonyPermissionEditDialog = ({
 
   // When selected user gets updates get that user's roles
   // to populate the checkboxes
-  const useSelectedUserForRoles = (): Array<string> => {
-    const { data } = useUserDomainRoles(colonyAddress, domain.id, selectedUser);
+  const { data } = useUserDomainRoles(colonyAddress, domain.id, selectedUser);
 
+  useEffect(() => {
```
Comment (sprusr) [inline src/modules/admin/components/Permissions/ColonyPermissionEditDialog.tsx]: Nice improvement, definitely wanted doing 👍

File: src/modules/admin/components/Permissions/ColonyPermissionEditDialog.tsx [hunk 2]
```diff
@@ -340,34 +307,25 @@ const ColonyPermissionEditDialog = ({
...
-                    <span className={styles.permissionChoiceDescription}>
-                      <Heading
-                        text={MSG[`role${id}`]}
-                        appearance={{ size: 'small', margin: 'none' }}
-                      />
-                      <FormattedMessage {...MSG[`roleDescription${id}`]} />
-                    </span>
-                  </Checkbox>
+                    role={role}
+                    roleDescription={MSG[`roleDescription${idx}`]}
```
Comment (sprusr) [inline src/modules/admin/components/Permissions/ColonyPermissionEditDialog.tsx]: How come move the message handling for the role name to `PermissionCheckbox` but not for the description?

Comment (ceolson01) [reply src/modules/admin/components/Permissions/ColonyPermissionEditDialog.tsx]: So the role names are actually in the `en/i18n.json` file, but `PermissionCheckbox` does indeed have the _logic_ to piece together the message id strings.

That said, perhaps it would make sense to move the description messages into `PermissionCheckbox` and use the role name to access each message... I think I'll do that

**Comment by ceolson01** [comment]
@sprusr I moved the role description messages into the `PermissionCheckbox` component, and also added styles to use the `pointer` cursor for checkboxes.

Before I merge this, could you please check out those last couple of changes?

File: src/modules/admin/components/Permissions/PermissionCheckbox.tsx [hunk 3]
```diff
@@ -33,9 +60,11 @@ const PermissionCheckbox = ({
   disabled,
   intl: { formatMessage },
   role,
-  roleDescription,
 }: Props) => {
   const roleNameMessage = { id: `role.${role.toLowerCase()}` };
+  const roleDescriptionMessage = MSG[
```
Comment (sprusr) [inline src/modules/admin/components/Permissions/PermissionCheckbox.tsx]: Could this be inside the `useMemo`?

Comment (ceolson01) [reply src/modules/admin/components/Permissions/PermissionCheckbox.tsx]: Yessir! Good catch, thank you 🙏
