### PR TITLE
Fixes permissions bug on unlock modal when token already unlocked

### LINKED ISSUE #2989: After unlocking your token you can no longer access the modal
After you unlock your token, you can no longer access that modal, since it tells you (wrongly) that you don't have the correct permissions. (you do, I just suspect we do a unlock token check which is not correct)

Screenshot from 2021-12-01 20-09-58

There's two ways of fixing this:
- allow you to access the modal, but tell you that the token is already unlocked and there's nothing for you to do (with the controls disabled of course)
- hide the menu entry if the token is unlocked

Please check with Product on which way they'd like us to fix it.

### PR DESCRIPTION
**Pull request by agustif**
## Description

- [x] allow you to access the modal, but tell you that the token is already unlocked and there's nothing for you to do (with the controls disabled of course)

**New stuff** ✨

* Added new unlockedTitle, and unlockedDescription, which are conditionally showed instead of the regular title & description when the NativeToken is Not Locked anymore.

**Changes** 🏗

* Where title and description are called, we check for colony.nativeTokenIsLocked, and if true we show the regular one, if false the unlocked one variants.

**Deletions** ⚰️

* Removed condition check colony.isNativeTokenLocked from canUnlockNativeToken (So permission error doesn't show when it's already Unlocked)

## TODO

- [x] Add new unlocked title and description messages
- [x] Remove permissions check if token unlocked
- [x] Show different versions of text if token alrady unlocked

Resolves #2989

### CODE REVIEW

File: src/modules/dashboard/components/UnlockTokenDialog/UnlockTokenForm.tsx [hunk 1]
```diff
@@ -39,6 +39,14 @@ const MSG = defineMessages({
     defaultMessage: `You do not have the {roleRequired} permission required
       to take this action.`,
   },
+  unlockedTitle: {
+    id: 'dashboard.UnlockTokenDialog.UnlockTokenForm.dialogunlockedTitle',
```
Comment (ArmandoGraterol) [inline src/modules/dashboard/components/UnlockTokenDialog/UnlockTokenForm.tsx:43]: Typo here, should be `.unlockedTitle`

File: src/modules/dashboard/components/ManageFundsDialog/ManageFundsDialog.tsx [hunk 2]
```diff
@@ -118,9 +118,7 @@ const ManageFundsDialog = ({
     : colony.canMintNativeToken && hasRoot(allUserRoles);
   const canUnlockToken = isVotingExtensionEnabled
     ? colony.isNativeTokenLocked && colony.canUnlockNativeToken
```
Comment (ArmandoGraterol) [inline src/modules/dashboard/components/ManageFundsDialog/ManageFundsDialog.tsx:120]: You also need to change this condition, as of now I can't access the dialog even if I have root permission when the voting reputation extension is enabled:
FireShot Capture 504 - Colony - localhost

**Review by ArmandoGraterol — CHANGES_REQUESTED** [review]
The non-reputation version of the modal seems to be working as expected, however, the voting rep version is still not accesible.

File: src/modules/dashboard/components/UnlockTokenDialog/UnlockTokenForm.tsx (hunk 1 above)
Comment (agustif) [reply src/modules/dashboard/components/UnlockTokenDialog/UnlockTokenForm.tsx:43]: Good one, thanks for spotting, fixed on new commit

File: src/modules/dashboard/components/ManageFundsDialog/ManageFundsDialog.tsx (hunk 2 above)
Comment (agustif) [reply src/modules/dashboard/components/ManageFundsDialog/ManageFundsDialog.tsx:120]: I've fixed it by removing `colony.isNativeTokenLocked &&` in line 120.

Tested by enabling motions and working as expected, thanks for catching this as I didn't think of it

**Review by ArmandoGraterol — APPROVED** [review]
Yep, now I can access it with or without the voting reputation extension :+1:

**Review by rdig — CHANGES_REQUESTED** [review]
All good, except the warning should not show up at all, when the token is unlocked already.

File: src/modules/dashboard/components/UnlockTokenDialog/UnlockTokenForm.tsx [hunk 3]
```diff
@@ -81,7 +88,11 @@ const UnlockTokenForm = ({
...
       )}
       <DialogSection appearance={{ theme: 'sidePadding' }}>
-        <FormattedMessage {...MSG.description} />
+        {colony.isNativeTokenLocked ? (
+          <FormattedMessage {...MSG.description} />
+        ) : (
+          <FormattedMessage {...MSG.unlockedDescription} />
+        )}
       </DialogSection>
       <DialogSection appearance={{ theme: 'sidePadding' }}>
```
[the remark this answers is not in the document]
Comment (agustif) [reply src/modules/dashboard/components/UnlockTokenDialog/UnlockTokenForm.tsx:97]: Yeah makes sense was silly to leave it, will hide the notice when unlocked. Thanks Raul

[the remark this answers is not in the document]
Comment (agustif) [reply src/modules/dashboard/components/UnlockTokenDialog/UnlockTokenForm.tsx:97]: Fixed now on last commit, I added an unlocked style to add margin-bottom 20px, since hiding the notice made the description have no margin-bottom.

image

**Review by rdig — APPROVED** [review]
Good to go!
