### PR TITLE
Fix & consolidate the whole set of cypress tests

### LINKED ISSUE #3299: Check that all of the tests are running from start to finish without any additional inputs
Once #3298 & #3261 are done.

### PR DESCRIPTION
**Pull request by chinins**
## Description

This consolidates all the tests. To run it properly, you need to do it first thing after you start the dev environment.

Remember to have the reputation monitor on.

This needs to be run in a headless mode with `npm run cy:run` command. You also  need to change a cypress variable `skipInitTests` to false.

Sometimes annotations don't get through and this causes a test to fail although it all worked fine. Not sure how to deal with it yet...

## TODO

Refactor restructuring of the config variables where they are used.

resolves #3299

### CODE REVIEW

**Review by arrenv — COMMENTED** [review]
We are going to have a merge conflict with this and https://github.com/JoinColony/colonyDapp/pull/3261, I refactored based on Raul's feedback. I will likely need to undo my updates it seems.

File: cypress/e2e/2-createColony.js [hunk 1]
```diff
@@ -1,21 +1,25 @@
 describe('Create a new colony', () => {
   if (!Cypress.config().skipInitTests) {
     it('creates a new colony with new token', () => {
-      const { name, nativeToken } = Cypress.config().colony;
+      const { colony, baseUrl } = Cypress.config();
```
Comment (rdig) [inline cypress/e2e/2-createColony.js:4]: Does the config need to be called every time, or can we do this somewhere at the start of the file, somewhere inside the `describe` declaration, but outside of any individual `it` declarations

Not major, just a thought

**Review by rdig — APPROVED** [review]
Looks good to me. Nice work!

File: cypress/e2e/2-createColony.js (hunk 1 above)
Comment (chinins) [reply cypress/e2e/2-createColony.js:4]: Yeah, I already thought about it. But it seems that Arren has already refactored it everywhere. I need to wait until he merges his PR first so that I can make the final pass at all the tests. And then I'll make sure that it's consistent across all the files.

**Review by ArmandoGraterol — APPROVED** [review]
After much pain and adjustments, managed to pass all the tests from start to finish! Nice work

**Comment by dit7ya** [comment]
I tried to run the tests but this is what happened in the second test and every other test failed after that.

**Comment by chinins** [comment]
> I tried to run this so that I can start working on #3252 but I am getting the following on the second test - and every other test after that just fails. Any clue what might be the reason?
> 


You also  need to change a cypress variable `skipInitTests` to false.
