### PR TITLE
UX Improvements to members list views

### LINKED ISSUE #3002: "Members: All Teams" doesn't show wallets with accrued reputation
## Steps to reproduce

1. Check out Swashbuckle's view ([link](https://qaxdai.colony.io/colony/roadrunner/members))
2. Switch to Root view 

image

image

## Expected behaviour

* All Team's view shows all users who are watching + users with reputation (basically hybrid of Root + All)

## Actual behaviour

* Appears to only show users, not wallets

## Thoughts

* If a member is part of the root view, they should most likely be in the All view.
* The reason this leads to a potential issue is that the reputation doesn't add up to 100% within the All view, which is nonsensical from a UX perspective.

### PR DESCRIPTION
**Pull request by arrenv**
## Description

Makes improvements to the members list view. 

1. Ensuring all addresses with reputation in root, also appear within the "All teams" view. This solution continues with the limitations of the current query as mentioned in PR #2981

2. Sorts the users within the "All teams" view by reputation.

all-teams-view

3. Improves the loading of individual members

loading-in-members

4. Fixes banned tag not showing within teams.

Screenshot 2021-12-13 111807

## TODO

- [x] Add sorting by reputation to "All teams"
- [x] Include non-subscribers with reputation in "All teams"
- [x] Banned user tags in all team views
- [x] Better loading of each team member

Resolves #3002

### CODE REVIEW

File: src/modules/core/components/MembersList/MembersListItem.tsx [hunk 1]
```diff
@@ -72,7 +81,11 @@ const MembersListItem = <U extends AnyUser = AnyUser>(props: Props<U>) => {
       {/* Disable, as `role` is conditional */}
       {/* eslint-disable-next-line jsx-a11y/no-static-element-interactions */}
       <div
-        className={getMainClasses({}, styles, { hasCallbackFn: !!onRowClick })}
+        className={getMainClasses({}, styles, {
+          hasCallbackFn: !!onRowClick,
+          hasReputation: !!showUserReputation,
+          reputationLoaded: !!reputationLoaded,
```
Comment (chinins) [inline src/modules/core/components/MembersList/MembersListItem.tsx:87]: why do you have to negations here if it's already a boolean?

Comment (chinins) [inline src/modules/core/components/MembersList/MembersListItem.tsx:87]: Why do you have to negations here as it's already a boolean?

**Review by chinins — APPROVED** [review]
Looks good - nice work!

**Review by ArmandoGraterol — CHANGES_REQUESTED** [review]
I think the changes to `MemberReputation` also affected the reputation in the navbar because this:
FireShot Capture 509 - Colony - localhost

It's now looking like this:

FireShot Capture 510 - Colony - localhost

This is how it looks when you aren't in a colony and you are logged in, like in the `/landing` page

**Comment by chinins** [comment]
> I think the changes to `MemberReputation` also affected the reputation in the navbar because this: FireShot Capture 509 - Colony - localhost
> 
> It's now looking like this:
> 
> FireShot Capture 510 - Colony - localhost
> 
> This is how it looks when you aren't in a colony and you are logged in, like in the `/landing` page

Interesting, this is how it looks on my machine - same case, actually same as on master:
Screenshot 2021-12-14 at 16 31 16

**Comment by ArmandoGraterol** [comment]
@chinins Oof, so weird! I just took a look again just to be sure that I wasn't crazy and I can confirm that it still looks like the screenshots I uploaded above

File: src/modules/core/components/MembersList/MembersListItem.tsx (hunk 1 above)
Comment (arrenv) [reply src/modules/core/components/MembersList/MembersListItem.tsx:87]: It is pretty redundant, I will remove.

File: src/modules/core/components/MemberReputation/MemberReputation.tsx [hunk 2]
```diff
@@ -59,23 +61,31 @@ const MemberReputation = ({
     userReputationData?.userReputation,
     totalReputation?.userReputation,
   );
+
+  useEffect(() => {
+    if (userReputationData) {
+      onReputationLoaded(true);
+    } else {
+      onReputationLoaded(false);
+    }
```
[the remark this answers is not in the document]
Comment (arrenv) [reply src/modules/core/components/MemberReputation/MemberReputation.tsx:70]: Much cleaner, thank you!

**Comment by arrenv** [comment]
@ArmandoGraterol I have not been able to replicate either, however, I think I know why you may have seen this. Could you please try testing again now.

**Review by ArmandoGraterol — APPROVED** [review]
It looks as expected now! Thank you Arren.

Also, I really like the improvements. Good job :ok_hand:
