### PR TITLE
Fix annotations transaction failure

### LINKED ISSUE #2654: Transaction failure when trying to annotate the Mint Tokens action
## Steps to reproduce

1. Create a token called $UNIT
2. Mint tokens

## Expected behaviour

* If we can't handle this type of symbol, we should throw an error when creating your token symbol.

## Actual behaviour

* User is approved when creating the token symbol.

## Suggestions (optional)

* Another way to solve this quickly would be to add some copy about our expectations, but given the user is effectively stuck once they do this — we should probably prevent it from happening.

### PR DESCRIPTION
**Pull request by chinins**
## Description

This PR fixes the error that we have when ipfs fails to upload an annotation (both for motion & action). The action and motion both go through but because there is an error in annotation (you can't upload null, but need a string), there is no redirect.

The fix I implemented is to try again and if it failed again then just assign an empty string.

I had a problem with types when I pushed my commits from the `versionUpgrade` action so I just copy pasted the code instead of calling a helper. Hopefully will find out why it happens & fix it.

resolves #2654

### CODE REVIEW

File: src/modules/dashboard/sagas/utils/uploadIfpsAnnotation.ts [hunk 1]
```diff
@@ -0,0 +1,28 @@
+import { call } from 'redux-saga/effects';
+import { ipfsUpload } from '../../../core/sagas/ipfs';
+
+export function* uploadIfpsAnnotation(annotationMessage: string) {
+  let ipfsHash: string | null = null;
```
Comment (arrenv) [inline src/modules/dashboard/sagas/utils/uploadIfpsAnnotation.ts:5]: Nice work, bringing it all in here, much cleaner.

Is it worth wrapping in a try/catch to add further redundancy here?

**Review by arrenv — APPROVED** [review]
This one is a difficult to replicate, unless you have a super fast machine it seems.

However, these updates seem to work well and makes sense. I have added some notes, one which fixes the typing issue you were having in `versionUpgrade`.

File: src/modules/dashboard/sagas/utils/uploadIfpsAnnotation.ts (hunk 1 above)
Comment (chinins) [reply src/modules/dashboard/sagas/utils/uploadIfpsAnnotation.ts:5]: Not really, ipfs just fails without an error so it won't do anything.

File: src/modules/dashboard/sagas/actions/versionUpgrade.ts [hunk 2]
```diff
@@ -96,14 +97,28 @@ function* createVersionUpgradeAction({
     if (supportAnnotation) {
```
[the remark this answers is not in the document]
Comment (chinins) [reply src/modules/dashboard/sagas/actions/versionUpgrade.ts]: Yeah, I was thinking that though a bit redundant it might fix it and it did. Updated now, plus added the comment to track it.

**Review by alicjakujawa — COMMENTED** [review]
I feel that we could just put call to ipfsUpload in try/catch block and assign ipfsHash to empty string in catch block, not sure if all of this here is needed

**Comment by chinins** [comment]
> I feel that we could just put call to ipfsUpload in try/catch block and assign ipfsHash to empty string in catch block, not sure if all of this here is needed

`ipfsUpload` already uses try-catch block inside and we have it in the saga itself. This is to guard when it fails silently. It's hard to replicate but when it does we have an error in a different transaction because we can't use null as an argument, only a string.

**Review by ArmandoGraterol — APPROVED** [review]
I haven't been able to replicate the issue, however, the annotations work as expected and the changes made make sense to me so it's good to go!
