### PR TITLE
Fix apollo error in user resolver

### LINKED ISSUE #3078: Apollo error when trying to create a payment
This is coming from a query in createPayment action. The action actually goes through and it appears in the list if I close the dialog.
Screenshot 2021-12-27 at 15 50 48

### PR DESCRIPTION
**Pull request by chinins**
## Description

This PR adds a try catch block around initiation of voting extension client in user resolver. If we don't do it and the voting extension is not installed then we will get an apollo error when creating a payment. This is because we use a query in the create payment saga that uses this resolver.

Resolves #3078

### CODE REVIEW

**Comment by arrenv** [comment]
@chinins This seems to trigger the error always now. As in, just reloading the page causes the error.

error-with-no-action

**Review by arrenv — CHANGES_REQUESTED** [review]
As of previous comment.

File: src/data/resolvers/user.ts [hunk 1]
```diff
@@ -140,10 +140,16 @@ const getUserLock = async (
...
-  );
+  let votingReputationClient;
+
+  try {
+    votingReputationClient = await colonyManager.getClient(
+      ClientType.VotingReputationClient,
+      colonyAddress,
+    );
+  } catch (error) {
+    console.error(error);
```
Comment (arrenv) [inline src/data/resolvers/user.ts:151]: Removing the console.log should do the trick to remove the error. Otherwise, this PR fixes the main error.

**Review by arrenv — CHANGES_REQUESTED** [review]

**Comment by chinins** [comment]
> @chinins This seems to trigger the error always now. As in, just reloading the page causes the error.
> 
> error-with-no-action

Yeah, I guess it's not worth even logging it. I've changed it to `silent` error now.

**Review by arrenv — APPROVED** [review]
Nice, works well for me, no more errors.

**Review by ArmandoGraterol — APPROVED** [review]
Good job :100:
