### PR TITLE
Fix description field (for good this time?)

### LINKED ISSUE #1740: Task descriptions not displaying
## Steps to reproduce

1. Create a task with a title and description.
2. Refresh

## Expected behaviour

The text description text should be visible.

## Actual behaviour

image

Note: it is only on tasks that I created that I cannot view the description and I cannot reproduce this on QA.
Here is the task from the screenshot: https://colony.io/colony/speaketh/task/jGagdIUyHUgxxeaqu3WiG

### PR DESCRIPTION
**Pull request by chmanie**
## Description

This PR aims to fix the description field sometimes not rendering properly. We stored the state of the field as an `EditorState` object in formik which caused all sorts of troubles (when comparing it to the data before, etc.). With the change we're storing it as a `string` now when the user blurs out of the field. This should give formik the opportunity to compare the old and new values properly.

**Changes** 🏗

* Store `MultiLineEdit` state as a string in formik
* Convert `MultiLineEdit` into a functional component

**Deletions** ⚰️

* Remove `useInitEditorState` hook

Resolves #1740

### CODE REVIEW

File: src/modules/core/components/Fields/InlineEdit/MultiLineEdit/MultiLineEdit.tsx [hunk 1]
```diff
@@ -92,112 +90,86 @@ interface Props {
...
+  setValue,
+  status,
+  statusValues,
+  elementOnly = true,
+  readOnly = false,
+  spellCheck = false,
+}: Props) => {
+  const prevValue = usePrevious($value);
+  const initialEditorState =
+    $value && prevValue !== $value
```
Comment (chmanie) [inline src/modules/core/components/Fields/InlineEdit/MultiLineEdit/MultiLineEdit.tsx]: Even though it seems to work, I just thought about this and I think the condition here is wrong. Why should it be empty when the previous value is the same as the current one?

**Comment by chmanie** [comment]
Would you mind to try again with the revised version?

File: src/modules/core/components/Fields/InlineEdit/MultiLineEdit/MultiLineEdit.tsx [hunk 2]
```diff
@@ -92,112 +89,87 @@ interface Props {
...
+    () => (!allowReturns ? HANDLED : NOT_HANDLED),
+    [allowReturns],
+  );
+  const onBlur = useCallback(
+    (evt: FocusEvent) => {
+      if (onEditorBlur) {
+        const content = editorState.getCurrentContent();
+        const newValue =
+          (content.hasText() && content.getPlainText().trim()) || '';
+        if (newValue !== $value) setValue(newValue);
```
Comment (ceolson01) [inline src/modules/core/components/Fields/InlineEdit/MultiLineEdit/MultiLineEdit.tsx]: Shouldn't this execute even if `onEditorBlur` is `undefined`?

Comment (chmanie) [reply src/modules/core/components/Fields/InlineEdit/MultiLineEdit/MultiLineEdit.tsx]: You're right, I'll adjust!

**Comment by chmanie** [comment]
> This doesn't seem to protect against a user entering nothing but spaces

OK, let's see whether I can fix this

File: src/modules/core/components/Fields/InlineEdit/MultiLineEdit/MultiLineEdit.tsx [hunk 3]
```diff
@@ -92,112 +89,87 @@ interface Props {
...
+  const handleReturn = useCallback(
+    () => (!allowReturns ? HANDLED : NOT_HANDLED),
+    [allowReturns],
+  );
+  const onBlur = useCallback(
+    (evt: FocusEvent) => {
+      if (onEditorBlur) {
+        const content = editorState.getCurrentContent();
+        const newValue =
+          (content.hasText() && content.getPlainText().trim()) || '';
```
Comment (chmanie) [inline src/modules/core/components/Fields/InlineEdit/MultiLineEdit/MultiLineEdit.tsx]: I actually thought the `.trim()` would take care of the spaces issue. I'll look into it more
